In [6]:
from model import TransformerModel
import numpy as np
import torch
from Hamiltonian import Ising

In [7]:
Hamiltonian=Ising(np.array([4]), periodic=False)

C:\Users\nicol\OneDrive\Área de Trabalho\Coisas UFMG\Codigo Monografia\Trabalho_Monografia_Yuanhangzang_Code_main\Hamiltonian_utils.py:44: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  system_size = torch.tensor(system_size, dtype=torch.int64).reshape(-1)


In [8]:
param_dim=Hamiltonian.param_dim

In [9]:
embedding_size = 32
n_head = 8
n_hid = embedding_size
n_layers = 8
dropout = 0
minibatch = 10000

In [10]:
n=4
model1D=TransformerModel(np.array([[n]]), param_dim, embedding_size, n_head, n_hid, n_layers, dropout=dropout,
                         minibatch=minibatch)
param = torch.tensor([1], dtype=torch.get_default_dtype())
param[0]=0
system_sizes = torch.tensor([[n]], dtype=torch.int64, device='cpu')
model1D.set_param(param=param,system_size=system_sizes[0])

C:\Users\nicol\AppData\Roaming\Python\Python39\site-packages\torch\nn\modules\transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


In [11]:
from model_utils import *

In [12]:
samples,weights=sample(model1D,max_unique=5,batch=2)

src_i tensor([[[0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]])
output_i tensor([[[-0.0389,  0.3205,  0.0893,  1.7379,  0.8099, -0.8223, -0.0938,
          -0.0910, -0.2508, -1.5088, -1.2200,  0.8373, -0.5606,  0.0029,
          -1.5942, -0.3361,  1.5477, -0.7648,  0.3967, -0.3918,  0.6294,
          -1.4561, -0.1922,  0.1483,  0.4083,  1.1168, -0.8034,  2.2873,
           1.1731, -0.5008, -1.9970,  1.1172]],

        [[-0.3507, -1.0518,  0.0059,  0.4969,  1.2293, -1.1954,  0.3812,
           0.4479, -1.5707, -1.8801, -1.1597,  1.1946, -0.9162,  1.0088,
          -1.4411,  0.0074,  1.8715,  0.7614,  1.0461,  1.5921, -0.3649,
          -0.9667,  0.2676,  0.7765,  1.2243,  0.5087, -1.1069,  0.3225,
           0.6886, -0.8786, -0.8568, -0.0916]]])
src_i tensor([[[0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.000

In [13]:
compute_psi(model1D,samples)[0].exp()

src_i tensor([[[0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000]]])
output_i tensor([[[-0.0389,  0.3205,  0.0893,  1.7379,  0.8099, -0.8223, -0.0938,
          -0.0910, -0.2508, -1.5088, -1.2200,  0.8373, -0.5606,  0.0029,
          -1.5942, -0.3361,  1.5477, -0.7648,  0.3967, -0.3918,  0.6294,
          -1.4561, -0.1922,  0.1483,  0.4083, 

NameError: name 'og_amp' is not defined

In [54]:
torch.tensor([[-0.6306, -0.6306, -0.6306, -0.6306, -0.7599, -0.7599, -0.7599, -0.7599],
        [-0.5833, -0.5833, -0.8166, -0.8166, -0.6034, -0.6034, -0.7918, -0.7918],
        [-0.6109, -0.7827, -0.6047, -0.7901, -0.5927, -0.8048, -0.6360, -0.7537]]).sum(0)

tensor([-1.8248, -1.9966, -2.0519, -2.2373, -1.9560, -2.1681, -2.1877, -2.3054])

In [19]:
x=torch.tensor([0.1985, 0.1007, 0.1039, 0.0468, 0.1067, 0.0451, 0.0529, 0.0223, 0.0973,
         0.0458, 0.0533, 0.0206, 0.0499, 0.0231, 0.0237, 0.0094])
x.sum(-1)

tensor(1.)

In [33]:
distribution = Binomial(total_count=10**5, probs=amps)

In [49]:
distribution.sample()

tensor([66410., 67564., 67379., 68031., 66803., 67621., 67630., 68676.])

In [17]:
model1D.wrap_spins(torch.tensor([[0., 1., 0., 1.],
        [0., 0., 1., 1.]]))

tensor([[[0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 1.3863, 0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000]]])